logfile was not working under daemonization.
Using a configuration file with these variables set will write to the
log file (using `gunicorn -c /tmp/conf1 test:app`):

    daemon = False
    logfile = '/tmp/log1'
    loglevel = 'debug'
    workers = 1

Using a configuration file with these variables set would not write to
the log (using `gunicorn -c /tmp/conf2 test:app`), it would be a zero
byte file.

    daemon = True
    logfile = '/tmp/log2'
    loglevel = 'debug'
    workers = 1

This patch makes that happen by reconfiguring logging after daemonization.
In order to prevent duplicate log messages, the log file handler should be
closed manually before the daemonization.

This patch comes with a bug report.  I wanted to test that this patch would
not wreak havoc when workers was set > 1, so I set workers = 5 (with daemon
= True) and looked at the logfile and got the error below and there were no
gunicorn processes left standing.

I git stash'd the changes and tried again.  The logfile was not available
(because of the original bug this patch is addressing) but there were also
no processes left standing.

===========

2010-06-05 15:15:32 [24197] [INFO] Worker spawned (pid: 24197)
2010-06-05 15:15:32 [24197] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/home/tim/dev/gunicorn/logbug/gunicorn/gunicorn/arbiter.py", line 389, in spawn_workers
    worker.init_process()
  File "/home/tim/dev/gunicorn/logbug/gunicorn/gunicorn/workers/base.py", line 95, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/tim/dev/gunicorn/logbug/gunicorn/gunicorn/app/base.py", line 78, in wsgi
    self.callable = self.load()
  File "/home/tim/dev/gunicorn/logbug/gunicorn/gunicorn/app/wsgiapp.py", line 25, in load
    return util.import_app(self.app_uri)
  File "/home/tim/dev/gunicorn/logbug/gunicorn/gunicorn/util.py", line 185, in import_app
    raise ImportError("Failed to find application object: %r" % obj)
ImportError: Failed to find application object: 'app'
2010-06-05 15:15:32 [24197] [INFO] Worker exiting (pid: 24197)